task_manager/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from django.conf import settings
from django.conf.urls.static import static


from tasks.views import TaskViewSet, UserViewSet

from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

router = routers.DefaultRouter()
router.register(r'notes', TaskViewSet, 'Note')
router.register(r'users', UserViewSet)



urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^tasks/', include('tasks.urls')),
    url(r'^', include('tasks.urls_visitor')),

    url(r'^api/', include(router.urls)), #rest api

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.conf.urls import url
from .import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView



app_name = 'tasks'

urlpatterns = [

    # # /webpages/
    url(r'^$', views.IndexView.as_view(), name='index'),
    #
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    #
    url(r'^login_user/$', LoginView.as_view(template_name='tasks/login.html'), name='login_user'),
    url(r'^logout_user/$', LogoutView.as_view(template_name='webpages/login.html'), name='logout_user'),
    #
    # # webpages/<sample_id>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    #
    # # /webpages/sample/add/
    url(r'task/add/$', views.TaskCreate.as_view(), name='task-add'),
    #
    # # /webpages/sample/2/
    url(r'task/(?P<pk>[0-9]+)/$', views.TaskUpdate.as_view(), name='task-update'),
    #
    # # /webpages/sample/2/delete/
    url(r'task/(?P<pk>[0-9]+)/delete/$', views.TaskDelete.as_view(), name='task-delete'),

]

tasks/models.py
from django.db import models
# from django.core.urlresolvers import reverse
from django.contrib.auth.models import Permission, User

from django.contrib.auth.models import AbstractUser, BaseUserManager

class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),

        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,

        )
        # user.is_admin = True
        user.save(using=self._db)
        return user



class User(AbstractUser):
    #user = models.OneToOneField(User, on_delete=models.CASCADE)
    projects = []
    tasks = []

    def add_project(self, project):
        self.projects.append(project)
        project.add_user(self)

    def add_task(self, task):
        self.tasks.append(task)
        return self.tasks

class Project(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)

    project_title = models.FileField()
    users = []
    tasks = []

    def add_task(self, task):
        self.tasks.append(task)
        return self.tasks

    def add_user(self, user):
        self.users.append(user)
        user.add_project(self)
    #
    # def get_absolute_url(self):
    #     return reverse('tasks:detail', kwargs={'pk': self.pk})

    def __str__(self):
       return self.project_title

class Task(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, default=1, on_delete=models.CASCADE)

    task_title = models.FileField()
    task_description = models.FileField()
    task_due_date = models.FileField()


    def get_absolute_url(self):
        return reverse('tasks:detail', kwargs={'pk': self.pk})

    def __str__(self):
        #return self.template_logo + '-' + self.template_title
        return self.task_title + '-' + self.task_description + '-' + self.task_due_date

tasks/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Project, Task

####################
from django.contrib.auth import get_user_model
User = get_user_model()
####################

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'is_staff', 'is_superuser']


class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ['project_title']

class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ['task_title', 'task_description', 'task_due_date']

tasks/views.py
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q

from .models import Project, Task
from django.http import HttpResponse
from django.template import loader

from django.views import generic
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy

from .forms import UserForm
from django.contrib.auth.mixins import LoginRequiredMixin

#############################

from django.utils.http import is_safe_url
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login, logout as auth_logout
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView

################
from rest_framework import viewsets
from rest_framework.decorators import api_view
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response

from tasks.serializers import TaskSerializer, UserSerializer
from tasks.models import User
################

from django.contrib.auth import login

class VisitorView(generic.TemplateView):
    template_name = 'tasks/base_visitor.html'

class IndexView(LoginRequiredMixin, generic.ListView):
    login_url = '/tasks/login_user'
    redirect_field_name = 'redirect_to'

    template_name = 'tasks/index.html'
    context_object_name = 'tasks' #all_samples

    def get_queryset(self):
        print(self.request.user)
        return Task.objects.filter(user=self.request.user)
        #return Task.objects.all()


class DetailView(LoginRequiredMixin, generic.DeleteView):
    login_url = '/tasks/login_user'
    redirect_field_name = 'redirect_to'

    model = Task
    template_name = 'tasks/detail.html'


class TaskCreate(LoginRequiredMixin, CreateView):
    login_url = '/tasks/login_user'
    redirect_field_name = 'redirect_to'

    model = Task
    fields = ['task_title', 'task_description', 'task_due_date']

    def form_valid(self, form):
        object = form.save(commit=False)
        object.user = self.request.user
        object.save()
        return super(TaskCreate, self).form_valid(form)

class TaskUpdate(LoginRequiredMixin, UpdateView):
    login_url = '/login_user/'
    redirect_field_name = 'redirect_to'

    model = Task
    fields = ['task_title', 'task_description', 'task_due_date']

    def form_valid(self, form):
        object = form.save(commit=False)
        object.user = self.request.user
        object.save()
        return super(TaskUpdate, self).form_valid(form)

class TaskDelete(LoginRequiredMixin, DeleteView):
    login_url = '/login_user/'
    redirect_field_name = 'redirect_to'

    model = Task
    success_url = reverse_lazy('tasks:index')

class UserFormView(View):
    form_class = UserForm
    template_name = 'tasks/register.html'

    #display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            # cleaned(normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns User objects if correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('tasks:index')
        return render(request, self.template_name, {'form': form})


class TaskViewSet(viewsets.ReadOnlyModelViewSet):
    """ List all of the notes for a user """
    permission_classes = (IsAuthenticated,)
    serializer_class = TaskSerializer

    def get_queryset(self):
        return Task.objects.filter(owner=self.request.user).order_by('-pub_date')


class UserViewSet(viewsets.ModelViewSet):
    permission_classes = (IsAuthenticated,)
    queryset = User.objects.all()
    serializer_class = UserSerializer

tasks/templates/tasks/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MuskTask{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="#"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'webpages/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
{#    <!--<script src="{% static 'music/js/main.js' %}"></script> -->#}
</head>


<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'base_visitor' %}">MuskTask</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block tasks_active %}{% endblock %}"><a href="{% url 'tasks:index' %}"><span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Tasks</a></li>
                {#                #}
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'tasks:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'tasks:task-add' %} ">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Task
                    </a>
                </li>
                <li>
                  <a href="{% url 'tasks:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

tasks/templates/tasks/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MuskTask{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="#"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'tasks/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
{#    <!--<script src="{% static 'music/js/main.js' %}"></script> -->#}
</head>


<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'base_visitor' %}">MuskTask</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
{#            <ul class="nav navbar-nav">#}
{#                <li class="{% block samples_active %}{% endblock %}"><a href="{% url 'webpages:index' %}"><span class="glyphicon glyphicon-th" aria-hidden="true"></span>&nbsp; Samples</a></li>#}
                {#                #}
{#            </ul>#}

            <ul class="nav navbar-nav navbar-right">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'tasks:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'tasks:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}


<h2 class="h22">Simple Task Manager</h2>

        <div class="panel-footer">
                    Don't have an account? <a href="{% url 'tasks:register' %}">Click here</a> to register.
        </div>

</body>
</html>

tasks/templates/tasks/detail.html
{% extends 'tasks/base.html' %}
{% block title %}{{ task }}{% endblock %}
{% block tasks_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Sample Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'tasks:detail' task.id %}">
{#                        {% if task.sample_logo %}#}
{#                            <img src="{{ sample.sample_logo.url }}" class="img-responsive">#}
{#                        {% else %}#}
{#                            <h3>No image to display</h3>#}
{#                        {% endif %}#}
                    </a>
                    <h1>{{ task.task_title }} </h1>

                </div>
            </div>
        </div>


    </div>

</div>

{% endblock %}

tasks/templates/tasks/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class ="col-sm-offset-2 col-sm-10">
            <span class ="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

tasks/templates/tasks/index.html
{% extends 'tasks/base.html' %}
{% block tasks_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Tasks -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Tasks</h3>
        </div>
        {% if tasks %}
            {% for task in tasks %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <!-- logo -->
                        <a href="{% url 'tasks:detail' task.id %}">
{#                            <img src="{{ task.sample_logo.url }}" class="img-responsive">#}
                        </a>
                        <div class="caption">
                            <h2>{{ task.task_title }}</h2>

                            <!-- View Details -->
                            <a href="{% url 'tasks:detail' task.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Sample -->
                            <form action="{% url 'tasks:task-delete' task.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="task_id" value="{{ task.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

{#                            <!-- Favorite Sample -->#}
{#                            <a href="#" class="btn btn-success btn-sm" role="button">Make Task#}
{#                            </a>#}

                        </div>
                    </div>
                </div>

            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="#">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Task
                    </button>
                </a>
            </div>
        {% endif %}
    </div>


</div>
{% endblock %}

tasks/templates/tasks/login.html
{% extends 'tasks/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'tasks:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'tasks:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

tasks/templates/tasks/register.html
 {% extends 'tasks/base.html' %}
 {% block title %} Register {% endblock %}


{% block body %}
<div class="container-fluid">

    <div class = "row">

        <div class = "col-sm col-md-7">
            <div class = "panel panel-default">
                <div class ="panel-body">
                    <h3> Create a new Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <form class ="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'tasks/form-template.html'%}
                        <div class = "form-group">
                            <div class = "col-sm-offset-2 col-sm-10">
                                <button type="submit" class = "btn btn-success"> Submit
                                </button>
                            </div>
                        </div>
                    </form>

                </div>

            </div>

        </div>

    </div>

</div>
{% endblock %}

tasks/templates/tasks/task_form.html
 {% extends 'tasks/base.html' %}
 {% block title %} Add a new task {% endblock %}
{% block tasks_active %} active {% endblock %}

{% block body %}
<div class="container-fluid">

    <div class = "row">

        <div class = "col-sm col-md-7">
            <div class = "panel panel-default">
                <div class ="panel-body">
                    <h3> Add a new Task</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}


                    <form class ="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'tasks/form-template.html'%}
                        <div class = "form-group">
                            <div class = "col-sm-offset-2 col-sm-10">
                                <button type="submit" class = "btn btn-success"> Submit
                                </button>
                            </div>
                        </div>
                    </form>

                </div>

            </div>

        </div>

    </div>

</div>
{% endblock %}